CREATE TABLE `nge_icl_languages` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `code` varchar(7) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `english_name` varchar(128) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `major` tinyint(4) NOT NULL DEFAULT '0',  `active` tinyint(4) NOT NULL,  `default_locale` varchar(35) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `tag` varchar(35) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `encode_url` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`),  UNIQUE KEY `code` (`code`),  UNIQUE KEY `english_name` (`english_name`)) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `nge_icl_languages` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `nge_icl_languages` VALUES('1', 'en', 'English', '1', '1', 'en_US', 'en', '0');
INSERT INTO `nge_icl_languages` VALUES('2', 'es', 'Spanish', '1', '0', 'es_ES', 'es', '0');
INSERT INTO `nge_icl_languages` VALUES('3', 'de', 'German', '1', '0', 'de_DE', 'de', '0');
INSERT INTO `nge_icl_languages` VALUES('4', 'fr', 'French', '1', '0', 'fr_FR', 'fr', '0');
INSERT INTO `nge_icl_languages` VALUES('5', 'ar', 'Arabic', '0', '0', 'ar', 'ar', '0');
INSERT INTO `nge_icl_languages` VALUES('6', 'bs', 'Bosnian', '0', '0', 'bs_BA', 'bs', '0');
INSERT INTO `nge_icl_languages` VALUES('7', 'bg', 'Bulgarian', '0', '0', 'bg_BG', 'bg', '0');
INSERT INTO `nge_icl_languages` VALUES('8', 'ca', 'Catalan', '0', '0', 'ca', 'ca', '0');
INSERT INTO `nge_icl_languages` VALUES('9', 'cs', 'Czech', '0', '0', 'cs_CZ', 'cs', '0');
INSERT INTO `nge_icl_languages` VALUES('10', 'sk', 'Slovak', '0', '0', 'sk_SK', 'sk', '0');
INSERT INTO `nge_icl_languages` VALUES('11', 'cy', 'Welsh', '0', '0', 'cy_GB', 'cy', '0');
INSERT INTO `nge_icl_languages` VALUES('12', 'da', 'Danish', '1', '0', 'da_DK', 'da', '0');
INSERT INTO `nge_icl_languages` VALUES('13', 'el', 'Greek', '0', '0', 'el', 'el', '0');
INSERT INTO `nge_icl_languages` VALUES('14', 'eo', 'Esperanto', '0', '0', 'eo_UY', 'eo', '0');
INSERT INTO `nge_icl_languages` VALUES('15', 'et', 'Estonian', '0', '0', 'et', 'et', '0');
INSERT INTO `nge_icl_languages` VALUES('16', 'eu', 'Basque', '0', '0', 'eu_ES', 'eu', '0');
INSERT INTO `nge_icl_languages` VALUES('17', 'fa', 'Persian', '0', '0', 'fa_IR', 'fa', '0');
INSERT INTO `nge_icl_languages` VALUES('18', 'fi', 'Finnish', '0', '0', 'fi', 'fi', '0');
INSERT INTO `nge_icl_languages` VALUES('19', 'ga', 'Irish', '0', '0', 'ga_IE', 'ga', '0');
INSERT INTO `nge_icl_languages` VALUES('20', 'he', 'Hebrew', '0', '0', 'he_IL', 'he', '0');
INSERT INTO `nge_icl_languages` VALUES('21', 'hi', 'Hindi', '0', '0', 'hi_IN', 'hi', '0');
INSERT INTO `nge_icl_languages` VALUES('22', 'hr', 'Croatian', '0', '0', 'hr', 'hr', '0');
INSERT INTO `nge_icl_languages` VALUES('23', 'hu', 'Hungarian', '0', '0', 'hu_HU', 'hu', '0');
INSERT INTO `nge_icl_languages` VALUES('24', 'hy', 'Armenian', '0', '0', 'hy_AM', 'hy', '0');
INSERT INTO `nge_icl_languages` VALUES('25', 'id', 'Indonesian', '0', '0', 'id_ID', 'id', '0');
INSERT INTO `nge_icl_languages` VALUES('26', 'is', 'Icelandic', '0', '0', 'is_IS', 'is', '0');
INSERT INTO `nge_icl_languages` VALUES('27', 'it', 'Italian', '1', '0', 'it_IT', 'it', '0');
INSERT INTO `nge_icl_languages` VALUES('28', 'ja', 'Japanese', '1', '0', 'ja', 'ja', '0');
INSERT INTO `nge_icl_languages` VALUES('29', 'ko', 'Korean', '0', '0', 'ko_KR', 'ko', '0');
INSERT INTO `nge_icl_languages` VALUES('30', 'ku', 'Kurdish', '0', '0', 'ku', 'ku', '0');
INSERT INTO `nge_icl_languages` VALUES('31', 'lv', 'Latvian', '0', '0', 'lv_LV', 'lv', '0');
INSERT INTO `nge_icl_languages` VALUES('32', 'lt', 'Lithuanian', '0', '0', 'lt_LT', 'lt', '0');
INSERT INTO `nge_icl_languages` VALUES('33', 'mk', 'Macedonian', '0', '0', 'mk_MK', 'mk', '0');
INSERT INTO `nge_icl_languages` VALUES('34', 'mt', 'Maltese', '0', '0', 'mt_MT', 'mt', '0');
INSERT INTO `nge_icl_languages` VALUES('35', 'mn', 'Mongolian', '0', '0', 'mn_MN', 'mn', '0');
INSERT INTO `nge_icl_languages` VALUES('36', 'ne', 'Nepali', '0', '0', 'ne', 'ne', '0');
INSERT INTO `nge_icl_languages` VALUES('37', 'nl', 'Dutch', '1', '0', 'nl_NL', 'nl', '0');
INSERT INTO `nge_icl_languages` VALUES('38', 'no', 'Norwegian Bokmål', '0', '0', 'nb_NO', 'no', '0');
INSERT INTO `nge_icl_languages` VALUES('39', 'pa', 'Punjabi', '0', '0', '', 'pa', '0');
INSERT INTO `nge_icl_languages` VALUES('40', 'pl', 'Polish', '0', '0', 'pl_PL', 'pl', '0');
INSERT INTO `nge_icl_languages` VALUES('41', 'pt-pt', 'Portuguese, Portugal', '0', '0', 'pt_PT', 'pt-pt', '0');
INSERT INTO `nge_icl_languages` VALUES('42', 'pt-br', 'Portuguese, Brazil', '0', '0', 'pt_BR', 'pt-br', '0');
INSERT INTO `nge_icl_languages` VALUES('43', 'qu', 'Quechua', '0', '0', 'quz_PE', 'qu', '0');
INSERT INTO `nge_icl_languages` VALUES('44', 'ro', 'Romanian', '0', '0', 'ro_RO', 'ro', '0');
INSERT INTO `nge_icl_languages` VALUES('45', 'ru', 'Russian', '1', '0', 'ru_RU', 'ru', '0');
INSERT INTO `nge_icl_languages` VALUES('46', 'sl', 'Slovenian', '0', '0', 'sl_SI', 'sl', '0');
INSERT INTO `nge_icl_languages` VALUES('47', 'so', 'Somali', '0', '0', 'so_SO', 'so', '0');
INSERT INTO `nge_icl_languages` VALUES('48', 'sq', 'Albanian', '0', '0', 'sq_AL', 'sq', '0');
INSERT INTO `nge_icl_languages` VALUES('49', 'sr', 'Serbian', '0', '0', 'sr_RS', 'sr', '0');
INSERT INTO `nge_icl_languages` VALUES('50', 'sv', 'Swedish', '0', '0', 'sv_SE', 'sv', '0');
INSERT INTO `nge_icl_languages` VALUES('51', 'ta', 'Tamil', '0', '0', 'ta_IN', 'ta', '0');
INSERT INTO `nge_icl_languages` VALUES('52', 'th', 'Thai', '0', '0', 'th', 'th', '0');
INSERT INTO `nge_icl_languages` VALUES('53', 'tr', 'Turkish', '0', '0', 'tr_TR', 'tr', '0');
INSERT INTO `nge_icl_languages` VALUES('54', 'uk', 'Ukrainian', '0', '0', 'uk', 'uk', '0');
INSERT INTO `nge_icl_languages` VALUES('55', 'ur', 'Urdu', '0', '0', 'uz_UZ', 'ur', '0');
INSERT INTO `nge_icl_languages` VALUES('56', 'uz', 'Uzbek', '0', '0', 'uz_UZ', 'uz', '0');
INSERT INTO `nge_icl_languages` VALUES('57', 'vi', 'Vietnamese', '0', '0', 'vi_VN', 'vi', '0');
INSERT INTO `nge_icl_languages` VALUES('58', 'yi', 'Yiddish', '0', '0', '', 'yi', '0');
INSERT INTO `nge_icl_languages` VALUES('59', 'zh-hans', 'Chinese (Simplified)', '1', '0', 'zh_CN', 'zh-hans', '0');
INSERT INTO `nge_icl_languages` VALUES('60', 'zu', 'Zulu', '0', '0', '', 'zu', '0');
INSERT INTO `nge_icl_languages` VALUES('61', 'zh-hant', 'Chinese (Traditional)', '1', '0', 'zh_TW', 'zh-hant', '0');
INSERT INTO `nge_icl_languages` VALUES('62', 'ms', 'Malay', '0', '0', 'ms_MY', 'ms', '0');
INSERT INTO `nge_icl_languages` VALUES('63', 'gl', 'Galician', '0', '0', 'gl_ES', 'gl', '0');
INSERT INTO `nge_icl_languages` VALUES('64', 'bn', 'Bengali', '0', '0', 'bn_BD', 'bn', '0');
INSERT INTO `nge_icl_languages` VALUES('65', 'kh', 'Khmer', '0', '1', 'km_KH', 'kh', '0');
/*!40000 ALTER TABLE `nge_icl_languages` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
