CREATE TABLE `nge_term_taxonomy` (  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `taxonomy` varchar(32) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `description` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',  `count` bigint(20) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_taxonomy_id`),  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),  KEY `taxonomy` (`taxonomy`)) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `nge_term_taxonomy` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `nge_term_taxonomy` VALUES('1', '1', 'category', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('2', '2', 'nav_menu', '', '0', '22');
INSERT INTO `nge_term_taxonomy` VALUES('3', '3', 'category', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('4', '4', 'category', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('5', '5', 'translation_priority', '', '0', '50');
INSERT INTO `nge_term_taxonomy` VALUES('6', '6', 'translation_priority', '', '0', '44');
INSERT INTO `nge_term_taxonomy` VALUES('7', '7', 'translation_priority', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('8', '8', 'translation_priority', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('9', '9', 'translation_priority', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('10', '10', 'translation_priority', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('11', '11', 'faq_cat', 'FAQ\'s page', '0', '8');
INSERT INTO `nge_term_taxonomy` VALUES('12', '12', 'nav_menu', '', '0', '22');
INSERT INTO `nge_term_taxonomy` VALUES('13', '13', 'elementor_library_type', '', '0', '7');
INSERT INTO `nge_term_taxonomy` VALUES('14', '14', 'elementor_library_category', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('15', '15', 'elementor_library_category', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('16', '16', 'elementor_library_category', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('17', '17', 'elementor_library_category', '', '0', '0');
INSERT INTO `nge_term_taxonomy` VALUES('18', '18', 'category', '', '0', '3');
INSERT INTO `nge_term_taxonomy` VALUES('19', '19', 'category', '', '0', '4');
INSERT INTO `nge_term_taxonomy` VALUES('20', '20', 'category', '', '0', '3');
INSERT INTO `nge_term_taxonomy` VALUES('21', '21', 'category', '', '0', '4');
INSERT INTO `nge_term_taxonomy` VALUES('22', '22', 'faq_cat', '', '0', '8');
/*!40000 ALTER TABLE `nge_term_taxonomy` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
