CREATE TABLE `nge_icl_string_urls` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `language` varchar(7) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `url` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `string_string_lang_url` (`language`,`url`(191))) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `nge_icl_string_urls` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `nge_icl_string_urls` VALUES('1', 'en', '/wp-admin/admin-ajax.php');
INSERT INTO `nge_icl_string_urls` VALUES('2', 'en', '/wp-admin/admin.php?page=monsterinsights_reports');
INSERT INTO `nge_icl_string_urls` VALUES('3', 'en', '/');
INSERT INTO `nge_icl_string_urls` VALUES('4', 'kh', NULL);
INSERT INTO `nge_icl_string_urls` VALUES('5', 'en', '/wp-admin/');
INSERT INTO `nge_icl_string_urls` VALUES('6', 'en', '(.?.+?)(?:/([0-9]+))?/?$');
INSERT INTO `nge_icl_string_urls` VALUES('7', 'en', 'ajax-request');
INSERT INTO `nge_icl_string_urls` VALUES('8', 'en', '/wp-admin/admin-ajax.php?action=itbub_http_loop_back_test&serial=i8n9riec6dkrjyx');
INSERT INTO `nge_icl_string_urls` VALUES('9', 'en', '/wp-admin/admin.php?page=pb_backupbuddy_backup');
INSERT INTO `nge_icl_string_urls` VALUES('10', 'en', '/wp-admin/admin-ajax.php?action=pb_backupbuddy_backupbuddy&function=quickstart_form');
INSERT INTO `nge_icl_string_urls` VALUES('11', 'en', '/wp-admin/admin.php?page=pb_backupbuddy_backup&quickstart_wizard=true');
INSERT INTO `nge_icl_string_urls` VALUES('12', 'en', '/wp-admin/admin-ajax.php?action=pb_backupbuddy_backupbuddy&function=profile_settings&profile=2&callback_data=2&');
INSERT INTO `nge_icl_string_urls` VALUES('13', 'en', '/wp-admin/admin-ajax.php?action=pb_backupbuddy_backupbuddy&function=exclude_tree');
INSERT INTO `nge_icl_string_urls` VALUES('14', 'en', '/wp-admin/admin.php?page=pb_backupbuddy_backup&backupbuddy_backup=2&after_destination=&delete_after=');
INSERT INTO `nge_icl_string_urls` VALUES('15', 'en', '/wp-admin/admin-ajax.php?action=pb_backupbuddy_backupbuddy&function=backup_status');
/*!40000 ALTER TABLE `nge_icl_string_urls` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
