CREATE TABLE `nge_icl_string_packages` (  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `kind_slug` varchar(160) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `kind` varchar(160) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `name` varchar(160) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `title` varchar(160) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `edit_link` text COLLATE utf8mb4_unicode_520_ci NOT NULL,  `view_link` text COLLATE utf8mb4_unicode_520_ci NOT NULL,  `post_id` int(11) DEFAULT NULL,  `word_count` varchar(2000) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `nge_icl_string_packages` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `nge_icl_string_packages` VALUES('1', 'page-builder-shortcode-strings', 'Page Builder ShortCode Strings', '8', 'Page Builder Page 8', '', '', '8', '{\"total\":131,\"to_translate\":{\"kh\":38}}');
INSERT INTO `nge_icl_string_packages` VALUES('2', 'page-builder-shortcode-strings', 'Page Builder ShortCode Strings', '60', 'Page Builder Page 60', '', '', '60', '{\"total\":362,\"to_translate\":{\"kh\":362}}');
INSERT INTO `nge_icl_string_packages` VALUES('5', 'page-builder-shortcode-strings', 'Page Builder ShortCode Strings', '68', 'Page Builder Page 68', '', '', '68', '{\"total\":0,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('6', 'gutenberg', 'Gutenberg', '463', 'Page Builder Page 463', '', '', '463', '{\"total\":73,\"to_translate\":{\"kh\":73}}');
INSERT INTO `nge_icl_string_packages` VALUES('7', 'gutenberg', 'Gutenberg', '469', 'Page Builder Page 469', '', '', '469', '{\"total\":73,\"to_translate\":{\"kh\":73}}');
INSERT INTO `nge_icl_string_packages` VALUES('8', 'page-builder-shortcode-strings', 'Page Builder ShortCode Strings', '469', 'Page Builder Page 469', '', '', '469', NULL);
INSERT INTO `nge_icl_string_packages` VALUES('9', 'gutenberg', 'Gutenberg', '470', 'Page Builder Page 470', '', '', '470', '{\"total\":52,\"to_translate\":{\"kh\":52}}');
INSERT INTO `nge_icl_string_packages` VALUES('10', 'gutenberg', 'Gutenberg', '471', 'Page Builder Page 471', '', '', '471', '{\"total\":225,\"to_translate\":{\"kh\":225}}');
INSERT INTO `nge_icl_string_packages` VALUES('11', 'gutenberg', 'Gutenberg', '472', 'Page Builder Page 472', '', '', '472', '{\"total\":81,\"to_translate\":{\"kh\":81}}');
INSERT INTO `nge_icl_string_packages` VALUES('12', 'gutenberg', 'Gutenberg', '473', 'Page Builder Page 473', '', '', '473', '{\"total\":56,\"to_translate\":{\"kh\":56}}');
INSERT INTO `nge_icl_string_packages` VALUES('13', 'gutenberg', 'Gutenberg', '474', 'Page Builder Page 474', '', '', '474', '{\"total\":738,\"to_translate\":{\"kh\":738}}');
INSERT INTO `nge_icl_string_packages` VALUES('14', 'gutenberg', 'Gutenberg', '475', 'Page Builder Page 475', '', '', '475', '{\"total\":204,\"to_translate\":{\"kh\":204}}');
INSERT INTO `nge_icl_string_packages` VALUES('17', 'page-builder-shortcode-strings', 'Page Builder ShortCode Strings', '634', 'Page Builder Page 634', '', '', '634', '{\"total\":387,\"to_translate\":{\"kh\":387}}');
INSERT INTO `nge_icl_string_packages` VALUES('21', 'elementor', 'Elementor', '706', 'Page Builder Page 706', '', '', '706', NULL);
INSERT INTO `nge_icl_string_packages` VALUES('22', 'elementor', 'Elementor', '719', 'Page Builder Page 719', '', '', '719', '{\"total\":448,\"to_translate\":{\"kh\":448}}');
INSERT INTO `nge_icl_string_packages` VALUES('23', 'elementor', 'Elementor', '722', 'Page Builder Page 722', '', '', '722', '{\"total\":5,\"to_translate\":{\"kh\":5}}');
INSERT INTO `nge_icl_string_packages` VALUES('24', 'elementor', 'Elementor', '728', 'Page Builder Page 728', '', '', '728', '{\"total\":6,\"to_translate\":{\"kh\":6}}');
INSERT INTO `nge_icl_string_packages` VALUES('25', 'elementor', 'Elementor', '730', 'Page Builder Page 730', '', '', '730', '{\"total\":502,\"to_translate\":{\"kh\":502}}');
INSERT INTO `nge_icl_string_packages` VALUES('27', 'elementor', 'Elementor', '755', 'Page Builder Page 755', '', '', '755', '{\"total\":410,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('28', 'elementor', 'Elementor', '760', 'Page Builder Page 760', '', '', '760', '{\"total\":221,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('29', 'elementor', 'Elementor', '800', 'Page Builder Page 800', '', '', '800', '{\"total\":215,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('31', 'elementor', 'Elementor', '853', 'Page Builder Page 853', '', '', '853', '{\"total\":759,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('32', 'elementor', 'Elementor', '874', 'Page Builder Page 874', '', '', '874', '{\"total\":200,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('33', 'elementor', 'Elementor', '877', 'Page Builder Page 877', '', '', '877', '{\"total\":115,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('34', 'elementor', 'Elementor', '915', 'Page Builder Page 915', '', '', '915', '{\"total\":299,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('35', 'elementor', 'Elementor', '919', 'Page Builder Page 919', '', '', '919', '{\"total\":249,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('36', 'elementor', 'Elementor', '925', 'Page Builder Page 925', '', '', '925', '{\"total\":139,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('37', 'elementor', 'Elementor', '932', 'Page Builder Page 932', '', '', '932', '{\"total\":451,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('38', 'elementor', 'Elementor', '937', 'Page Builder Page 937', '', '', '937', '{\"total\":315,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('39', 'elementor', 'Elementor', '998', 'Page Builder Page 998', '', '', '998', '{\"total\":256,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('40', 'elementor', 'Elementor', '1057', 'Page Builder Page 1057', '', '', '1057', '{\"total\":483,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('41', 'elementor', 'Elementor', '1062', 'Page Builder Page 1062', '', '', '1062', '{\"total\":225,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('42', 'elementor', 'Elementor', '1067', 'Page Builder Page 1067', '', '', '1067', '{\"total\":113,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('43', 'elementor', 'Elementor', '1075', 'Page Builder Page 1075', '', '', '1075', '{\"total\":39,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('44', 'elementor', 'Elementor', '1072', 'Page Builder Page 1072', '', '', '1072', '{\"total\":89,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('45', 'elementor', 'Elementor', '1084', 'Page Builder Page 1084', '', '', '1084', '{\"total\":362,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('46', 'elementor', 'Elementor', '1153', 'Page Builder Page 1153', '', '', '1153', '{\"total\":261,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('47', 'elementor', 'Elementor', '1156', 'Page Builder Page 1156', '', '', '1156', '{\"total\":216,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('48', 'elementor', 'Elementor', '1159', 'Page Builder Page 1159', '', '', '1159', '{\"total\":93,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('50', 'elementor', 'Elementor', '1169', 'Page Builder Page 1169', '', '', '1169', '{\"total\":107,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('51', 'elementor', 'Elementor', '1172', 'Page Builder Page 1172', '', '', '1172', '{\"total\":128,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('52', 'elementor', 'Elementor', '1176', 'Page Builder Page 1176', '', '', '1176', '{\"total\":269,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('53', 'elementor', 'Elementor', '1180', 'Page Builder Page 1180', '', '', '1180', '{\"total\":73,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('54', 'elementor', 'Elementor', '1183', 'Page Builder Page 1183', '', '', '1183', '{\"total\":51,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('55', 'elementor', 'Elementor', '1186', 'Page Builder Page 1186', '', '', '1186', '{\"total\":244,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('56', 'elementor', 'Elementor', '1189', 'Page Builder Page 1189', '', '', '1189', '{\"total\":231,\"to_translate\":{\"kh\":18}}');
INSERT INTO `nge_icl_string_packages` VALUES('57', 'elementor', 'Elementor', '1193', 'Page Builder Page 1193', '', '', '1193', '{\"total\":228,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('58', 'elementor', 'Elementor', '1196', 'Page Builder Page 1196', '', '', '1196', '{\"total\":251,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('59', 'elementor', 'Elementor', '1198', 'Page Builder Page 1198', '', '', '1198', '{\"total\":380,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('62', 'elementor', 'Elementor', '1226', 'Page Builder Page 1226', '', '', '1226', '{\"total\":153,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('63', 'elementor', 'Elementor', '1295', 'Page Builder Page 1295', '', '', '1295', '{\"total\":364,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('64', 'elementor', 'Elementor', '1404', 'Page Builder Page 1404', '', '', '1404', '{\"total\":370,\"to_translate\":{\"kh\":370}}');
INSERT INTO `nge_icl_string_packages` VALUES('65', 'elementor', 'Elementor', '1409', 'Page Builder Page 1409', '', '', '1409', '{\"total\":345,\"to_translate\":{\"kh\":345}}');
INSERT INTO `nge_icl_string_packages` VALUES('66', 'elementor', 'Elementor', '1401', 'Page Builder Page 1401', '', '', '1401', '{\"total\":46,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('67', 'elementor', 'Elementor', '1411', 'Page Builder Page 1411', '', '', '1411', '{\"total\":371,\"to_translate\":{\"kh\":371}}');
INSERT INTO `nge_icl_string_packages` VALUES('69', 'elementor', 'Elementor', '1650', 'Page Builder Page 1650', '', '', '1650', '{\"total\":2,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('71', 'page-builder-shortcode-strings', 'Page Builder ShortCode Strings', '1665', 'Page Builder Page 1665', '', '', '1665', '{\"total\":101,\"to_translate\":{\"en\":101}}');
INSERT INTO `nge_icl_string_packages` VALUES('72', 'page-builder-shortcode-strings', 'Page Builder ShortCode Strings', '1677', 'Page Builder Page 1677', '', '', '1677', '{\"total\":45,\"to_translate\":{\"kh\":1}}');
INSERT INTO `nge_icl_string_packages` VALUES('73', 'elementor', 'Elementor', '1726', 'Page Builder Page 1726', '', '', '1726', NULL);
INSERT INTO `nge_icl_string_packages` VALUES('75', 'elementor', 'Elementor', '1746', 'Page Builder Page 1746', '', '', '1746', NULL);
INSERT INTO `nge_icl_string_packages` VALUES('76', 'elementor', 'Elementor', '1751', 'Page Builder Page 1751', '', '', '1751', NULL);
INSERT INTO `nge_icl_string_packages` VALUES('79', 'elementor', 'Elementor', '1931', 'Page Builder Page 1931', '', '', '1931', '{\"total\":344,\"to_translate\":{\"kh\":344}}');
INSERT INTO `nge_icl_string_packages` VALUES('80', 'elementor', 'Elementor', '1937', 'Page Builder Page 1937', '', '', '1937', '{\"total\":512,\"to_translate\":{\"kh\":512}}');
INSERT INTO `nge_icl_string_packages` VALUES('81', 'elementor', 'Elementor', '1943', 'Page Builder Page 1943', '', '', '1943', '{\"total\":353,\"to_translate\":{\"kh\":353}}');
INSERT INTO `nge_icl_string_packages` VALUES('82', 'elementor', 'Elementor', '1950', 'Page Builder Page 1950', '', '', '1950', '{\"total\":248,\"to_translate\":{\"kh\":248}}');
INSERT INTO `nge_icl_string_packages` VALUES('83', 'elementor', 'Elementor', '1958', 'Page Builder Page 1958', '', '', '1958', '{\"total\":385,\"to_translate\":{\"kh\":385}}');
INSERT INTO `nge_icl_string_packages` VALUES('84', 'elementor', 'Elementor', '2132', 'Page Builder Page 2132', '', '', '2132', '{\"total\":56,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('85', 'elementor', 'Elementor', '2279', 'Page Builder Page 2279', '', '', '2279', '{\"total\":2,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('86', 'elementor', 'Elementor', '2282', 'Page Builder Page 2282', '', '', '2282', '{\"total\":2,\"to_translate\":{\"kh\":0}}');
INSERT INTO `nge_icl_string_packages` VALUES('87', 'elementor', 'Elementor', '2202', 'Page Builder Page 2202', '', '', '2202', '{\"total\":168,\"to_translate\":{\"kh\":0}}');
/*!40000 ALTER TABLE `nge_icl_string_packages` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
