CREATE TABLE `nge_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `slug` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`(191)),  KEY `name` (`name`(191))) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `nge_terms` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `nge_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `nge_terms` VALUES('2', 'Main Menu', 'main-menu', '0');
INSERT INTO `nge_terms` VALUES('3', 'Uncategorized @th', 'uncategorized-th', '0');
INSERT INTO `nge_terms` VALUES('4', 'Uncategorized @kh', 'uncategorized-kh', '0');
INSERT INTO `nge_terms` VALUES('5', 'Optional', 'optional', '0');
INSERT INTO `nge_terms` VALUES('6', 'Optional', 'optional-kh', '0');
INSERT INTO `nge_terms` VALUES('7', 'Required', 'required', '0');
INSERT INTO `nge_terms` VALUES('8', 'Required', 'required-kh', '0');
INSERT INTO `nge_terms` VALUES('9', 'Not needed', 'not-needed', '0');
INSERT INTO `nge_terms` VALUES('10', 'Not needed', 'not-needed-kh', '0');
INSERT INTO `nge_terms` VALUES('11', 'FAQ Page', 'faq-article', '0');
INSERT INTO `nge_terms` VALUES('12', 'Main Menu - Khmer', 'main-menu-khmer', '0');
INSERT INTO `nge_terms` VALUES('13', 'page', 'page', '0');
INSERT INTO `nge_terms` VALUES('14', 'Productivity', 'productivity', '0');
INSERT INTO `nge_terms` VALUES('15', 'People &amp; Staff Culture', 'people-staff-culture', '0');
INSERT INTO `nge_terms` VALUES('16', 'Business Basics', 'business-basics', '0');
INSERT INTO `nge_terms` VALUES('17', 'Leadership', 'leadership', '0');
INSERT INTO `nge_terms` VALUES('18', 'Productivity', 'productivity', '0');
INSERT INTO `nge_terms` VALUES('19', 'Business Basics', 'business-basics', '0');
INSERT INTO `nge_terms` VALUES('20', 'People &amp; Staff Culture', 'people-staff-culture', '0');
INSERT INTO `nge_terms` VALUES('21', 'Leadership', 'leadership', '0');
INSERT INTO `nge_terms` VALUES('22', 'FAQ Page', 'faq-article-kh', '0');
/*!40000 ALTER TABLE `nge_terms` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
